name: continuous integration

on: [push]

jobs:
  dbms-ci:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Install yarn dependencies
        run: yarn install --frozen-lockfile --prefer-offline
      - name: Run linter
        run: yarn lint
      - name: Run unit tests
        run: yarn test
